In [6]:
import numpy as np
import torch

In [4]:
t=np.array(np.random.random((5,5)))

In [9]:
t=torch.FloatTensor(np.random.randint(0,10,10))

In [13]:
t.dim(),t.shape,t.size(),t[0],t[1],t[2],t[0:3]

(1,
 torch.Size([10]),
 torch.Size([10]),
 tensor(7.),
 tensor(2.),
 tensor(7.),
 tensor([7., 2., 7.]))

In [36]:
t=torch.FloatTensor(np.random.randint(0,5,(5,5)))
s=torch.FloatTensor(np.random.randint(0,10,(5,2)))

In [37]:
t,s,t.matmul(s)

(tensor([[0., 0., 4., 0., 2.],
         [3., 0., 4., 3., 4.],
         [3., 2., 1., 3., 1.],
         [2., 3., 0., 3., 0.],
         [2., 1., 0., 1., 0.]]),
 tensor([[0., 1.],
         [1., 6.],
         [0., 9.],
         [1., 2.],
         [5., 4.]]),
 tensor([[10., 44.],
         [23., 61.],
         [10., 34.],
         [ 6., 26.],
         [ 2., 10.]]))

In [38]:
s.sum(),s.sum(axis=1),s.sum(axis=0)

(tensor(29.), tensor([1., 7., 9., 3., 9.]), tensor([ 7., 22.]))

In [39]:
s.mean(),s.mean(axis=1),s.mean(axis=0)

(tensor(2.9000),
 tensor([0.5000, 3.5000, 4.5000, 1.5000, 4.5000]),
 tensor([1.4000, 4.4000]))

In [40]:
s.argmax(axis=0),s.argmax(axis=1),s.argmax()

(tensor([4, 2]), tensor([1, 1, 1, 1, 0]), tensor(5))

## Section 2

In [41]:
s

tensor([[0., 1.],
        [1., 6.],
        [0., 9.],
        [1., 2.],
        [5., 4.]])

In [45]:
s.view(2,5)

tensor([[0., 1., 1., 6., 0.],
        [9., 1., 2., 5., 4.]])

In [46]:
u=torch.FloatTensor(np.random.randint(0,10,(3,3)))

In [47]:
u

tensor([[5., 1., 1.],
        [0., 8., 2.],
        [9., 5., 2.]])

In [55]:
u.view(3,3),u.T,u.squeeze(axis=1)

(tensor([[5., 1., 1.],
         [0., 8., 2.],
         [9., 5., 2.]]),
 tensor([[5., 0., 9.],
         [1., 8., 5.],
         [1., 2., 2.]]),
 tensor([[5., 1., 1.],
         [0., 8., 2.],
         [9., 5., 2.]]))

In [62]:
v=u.view(1,3,3)
v,v.squeeze(),v.shape,v.squeeze().shape

(tensor([[[5., 1., 1.],
          [0., 8., 2.],
          [9., 5., 2.]]]),
 tensor([[5., 1., 1.],
         [0., 8., 2.],
         [9., 5., 2.]]),
 torch.Size([1, 3, 3]),
 torch.Size([3, 3]))

In [ ]:
v.float().int()

In [76]:
torch.cat([u,u.T],axis=0),torch.cat([u,u.T],axis=1)

(tensor([[5., 1., 1.],
         [0., 8., 2.],
         [9., 5., 2.],
         [5., 0., 9.],
         [1., 8., 5.],
         [1., 2., 2.]]),
 tensor([[5., 1., 1., 5., 0., 9.],
         [0., 8., 2., 1., 8., 5.],
         [9., 5., 2., 1., 2., 2.]]))

In [77]:
torch.stack([u,u.T],axis=0),torch.stack([u,u.T],axis=1)

(tensor([[[5., 1., 1.],
          [0., 8., 2.],
          [9., 5., 2.]],
 
         [[5., 0., 9.],
          [1., 8., 5.],
          [1., 2., 2.]]]),
 tensor([[[5., 1., 1.],
          [5., 0., 9.]],
 
         [[0., 8., 2.],
          [1., 8., 5.]],
 
         [[9., 5., 2.],
          [1., 2., 2.]]]))

In [79]:
torch.stack([u,u.T],axis=0).shape,torch.stack([u,u.T],axis=2).shape

(torch.Size([2, 3, 3]), torch.Size([3, 3, 2]))

In [81]:
torch.ones_like(u),torch.zeros_like(u),

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [98]:
torch.tensor(np.eye(5)).byte()

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.uint8)

In [106]:
(u==1).bool()

tensor([[False,  True,  True],
        [False, False, False],
        [False, False, False]])