In [28]:
import numpy as np
import torch
import seaborn as sns
from torch import optim

In [111]:
x_train=torch.FloatTensor((np.random.random(1000)))
y_train=x_train*2 + (np.random.random(1000)-0.5)
W=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
nb_epochs=10000
optimizer=optim.SGD([W,b],lr=0.01)


In [112]:
for epoch in range(nb_epochs):
    hyperthesis=x_train*W+b
    cost=torch.mean((hyperthesis-y_train)**2)
    
    if epoch%1000==0:
        print("Epoch",epoch,"W",W.item(),"b",b.item())
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

Epoch 0 W 0.0 b 0.0
Epoch 1000 W 1.5577640533447266 b 0.23071077466011047
Epoch 2000 W 1.8592815399169922 b 0.0741310566663742
Epoch 3000 W 1.9395546913146973 b 0.03244468942284584
Epoch 4000 W 1.9609260559082031 b 0.021346427500247955
Epoch 5000 W 1.9666152000427246 b 0.018391910940408707
Epoch 6000 W 1.968127965927124 b 0.017606006935238838
Epoch 7000 W 1.968530535697937 b 0.017398033291101456
Epoch 8000 W 1.9686394929885864 b 0.017340239137411118
Epoch 9000 W 1.968644142150879 b 0.017337171360850334


## Lesson 04

In [136]:
x_train=torch.FloatTensor((np.random.randint(50,100,(1000,3))))
y_train=x_train.sum(axis=1)
W=torch.rand(3,requires_grad=True)
b=torch.rand(1,requires_grad=True)
nb_epochs=10000
optimizer=optim.SGD([W,b],lr=0.01)

In [137]:
for epoch in range(nb_epochs):
    hyperthesis=x_train.matmul(W)+b
    cost=torch.mean((hyperthesis-y_train)**2)
    
#     if epoch%1000==0:
#         print("Epoch",epoch,"W",W[0].item(),"b",b.item())
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

In [138]:
W,b

(tensor([nan, nan, nan], requires_grad=True),
 tensor([nan], requires_grad=True))

## Lesson 04-2


In [280]:
from torch.utils.data import Dataset

class MyDataSet(Dataset):
    def __init__(self):
        self.x_data=np.random.randint(10,20,(10000,3))
        self.y_data=self.x_data.sum(axis=1).reshape(-1,1) + np.random.random(10000).reshape(-1,1)
    def __len__(self):
        return len(self.x_data)
    def __getitem__(self,idx):
        x=torch.FloatTensor(self.x_data[idx])
        y=torch.FloatTensor(self.y_data[idx])
        
        return x,y
    
dataset=MyDataSet()

In [281]:
from torch.utils.data import DataLoader
dataloader=DataLoader(dataset,batch_size=1,shuffle=2)

In [285]:
for i,item in enumerate(dataloader):
    x,y=item
    print(x)
    print(y)
    print(x-y)
    break

tensor([[12., 12., 12.]])
tensor([[36.0993]])
tensor([[-24.0993, -24.0993, -24.0993]])


## Lesson 05


In [27]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [28]:
x_train=np.random.randint(1,6,(6,2))
y_train=x_data.sum(axis=1).reshape(-1,1)
print(x_data,y_data)

[[4 1 2]
 [1 4 5]
 [2 5 3]
 [5 2 1]
 [4 5 3]
 [1 4 3]] [[ 7]
 [10]
 [10]
 [ 8]
 [12]
 [ 8]]


In [51]:
# 모델 초기화
W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
x_train=torch.FloatTensor(x_train)
y_train=torch.FloatTensor(y_train)

In [82]:
x_data = np.random.randint(1,6,(6,2))
y_data =x_data.sum(axis=1).reshape(-1,1) > 6
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
x_train,y_train,x_train.shape,y_train.shape

(tensor([[1., 2.],
         [5., 2.],
         [1., 2.],
         [4., 3.],
         [2., 3.],
         [4., 5.]]),
 tensor([[0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [1.]]),
 torch.Size([6, 2]),
 torch.Size([6, 1]))

In [74]:
# 모델 초기화
W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}, {:.3f} {:.3f} '.format(
            epoch, nb_epochs, cost.item(),W[0].item(),W[1].item()
        ))

Epoch    0/1000 Cost: 0.693147, -1.167 -1.333 
Epoch  100/1000 Cost: 0.002315, -1.615 -1.786 
Epoch  200/1000 Cost: 0.001343, -1.793 -1.966 
Epoch  300/1000 Cost: 0.000949, -1.908 -2.081 
Epoch  400/1000 Cost: 0.000735, -1.993 -2.166 
Epoch  500/1000 Cost: 0.000600, -2.060 -2.233 
Epoch  600/1000 Cost: 0.000507, -2.116 -2.289 
Epoch  700/1000 Cost: 0.000439, -2.163 -2.336 
Epoch  800/1000 Cost: 0.000387, -2.205 -2.378 
Epoch  900/1000 Cost: 0.000346, -2.242 -2.415 
Epoch 1000/1000 Cost: 0.000313, -2.275 -2.448 


In [320]:
hyperthesis

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0

In [83]:
# 모델 초기화
W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = F.binary_cross_entropy(hypothesis,y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}, {:.3f} {:.3f} '.format(
            epoch, nb_epochs, cost.item(),W[0].item(),W[1].item()
        ))

Epoch    0/1000 Cost: 0.693147, 0.750 0.250 
Epoch  100/1000 Cost: 0.051957, 3.922 -1.931 
Epoch  200/1000 Cost: 0.030554, 4.752 -2.267 
Epoch  300/1000 Cost: 0.021944, 5.280 -2.479 
Epoch  400/1000 Cost: 0.017213, 5.671 -2.636 
Epoch  500/1000 Cost: 0.014199, 5.983 -2.761 
Epoch  600/1000 Cost: 0.012102, 6.243 -2.866 
Epoch  700/1000 Cost: 0.010555, 6.466 -2.955 
Epoch  800/1000 Cost: 0.009364, 6.662 -3.034 
Epoch  900/1000 Cost: 0.008419, 6.836 -3.103 
Epoch 1000/1000 Cost: 0.007650, 6.994 -3.166 


In [84]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis[:5])

tensor([[6.1964e-04],
        [1.0000e+00],
        [6.1964e-04],
        [9.9997e-01],
        [2.7690e-02]], grad_fn=<SliceBackward>)


In [85]:
prediction=hypothesis>=torch.FloatTensor([0.5])
print(prediction)

tensor([[False],
        [ True],
        [False],
        [ True],
        [False],
        [ True]])


In [87]:
print(prediction[:5].byte())
print(y_train[:5])

tensor([[0],
        [1],
        [0],
        [1],
        [0]], dtype=torch.uint8)
tensor([[0.],
        [1.],
        [0.],
        [1.],
        [0.]])


## Lesson 06

In [88]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [89]:
torch.manual_seed(1)

In [112]:
z=torch.FloatTensor([1,2,3])

In [113]:
hypothesis=F.softmax(z)

C:\Users\ipofri-desktop\anaconda3\envs\tch\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


In [114]:
hypothesis,hypothesis.sum()

(tensor([0.0900, 0.2447, 0.6652]), tensor(1.))

In [126]:
z=torch.rand(3,5,requires_grad=True)
hypothesis=F.softmax(z,dim=1)
hypothesis

tensor([[0.1870, 0.1983, 0.2767, 0.1586, 0.1794],
        [0.2612, 0.1765, 0.1704, 0.1374, 0.2546],
        [0.2134, 0.1698, 0.1517, 0.2291, 0.2360]], grad_fn=<SoftmaxBackward>)

In [128]:
y=torch.randint(5,(3,)).long()
y

tensor([0, 4, 0])

In [163]:
y_one_hot=torch.zeros_like(hypothesis)
y_one_hot.scatter_(1,y.unsqueeze(1),1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.]])

In [173]:
cost=(y_one_hot*-torch.log(hypothesis)).sum(dim=1).mean()
cost

tensor(1.5299, grad_fn=<MeanBackward0>)

### cross-entropy loss with torch.nn.functional

In [174]:
torch.log(F.softmax(z,dim=1))

tensor([[-1.6769, -1.6179, -1.2848, -1.8416, -1.7179],
        [-1.3425, -1.7346, -1.7699, -1.9845, -1.3682],
        [-1.5446, -1.7731, -1.8861, -1.4735, -1.4438]], grad_fn=<LogBackward>)

In [175]:
F.log_softmax(z,dim=1)

tensor([[-1.6769, -1.6179, -1.2848, -1.8416, -1.7179],
        [-1.3425, -1.7346, -1.7699, -1.9845, -1.3682],
        [-1.5446, -1.7731, -1.8861, -1.4735, -1.4438]],
       grad_fn=<LogSoftmaxBackward>)

In [181]:
r1=(y_one_hot*-torch.log(F.softmax(z,dim=1))).sum(dim=1).mean()
r2=F.nll_loss(F.log_softmax(z,dim=1),y)
r3=F.cross_entropy(z,y)
r1,r2,r3

(tensor(1.5299, grad_fn=<MeanBackward0>),
 tensor(1.5299, grad_fn=<NllLossBackward>),
 tensor(1.5299, grad_fn=<NllLossBackward>))

### training with log-level cross entropy loss

In [212]:
x_train = torch.randint(1,9,(8,4)).float()
y_train = torch.randint(0,3,(8,)).long()

In [218]:
W=torch.rand((4,3), requires_grad=True)
b=torch.rand((1,), requires_grad=True)

optimizer=optim.SGD([W,b],lr=0.01)
nb_epochs=10000

for epoch in range(nb_epochs+1):
    hypothesis=F.softmax(x_train.matmul(W)+b,dim=1)
    y_one_hot=torch.zeros_like(hypothesis)
    y_one_hot.scatter_(1,y_train.unsqueeze(1),1)
    cost = (y_one_hot * -torch.log(F.softmax(hypothesis, dim=1))).sum(dim=1).mean()
        
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 1000 == 0:
        print(epoch,cost.item())

0 1.1329989433288574
1000 0.8041098117828369
2000 0.7820568084716797
3000 0.7683035731315613
4000 0.757565975189209
5000 0.7486695051193237
6000 0.7411282062530518
7000 0.7346608638763428
8000 0.7290704846382141
9000 0.7242065072059631
10000 0.7199491262435913


In [217]:
W=torch.rand((4,3), requires_grad=True)
b=torch.rand((1,), requires_grad=True)

optimizer=optim.SGD([W,b],lr=0.01)
nb_epochs=10000

for epoch in range(nb_epochs+1):
    z=x_train.matmul(W)+b
    cost = F.cross_entropy(z,y_train)
        
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 1000 == 0:
        print(epoch,cost.item())

0 3.7239573001861572
1000 0.4803953170776367
2000 0.42412683367729187
3000 0.3848044276237488
4000 0.35365527868270874
5000 0.3279033899307251
6000 0.30607444047927856
7000 0.2872353494167328
8000 0.2707470953464508
9000 0.2561509907245636
10000 0.24310803413391113


### high level implementation with nn.module

In [224]:
class MySoftmaxClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(4,3)
    def forward(self,x):
        return self.linear(x)

In [225]:
model=MySoftmaxClassifier()

In [228]:
optimizer=optim.SGD(model.parameters(),lr=0.1)
nb_epochs=10000
for epoch in range(nb_epochs+1):
    prediction=model(x_train)
    cost=F.cross_entropy(prediction,y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%1000 == 0:
        print(epoch, cost.item())

0 0.1755819022655487
1000 0.10082922130823135
2000 0.06935933232307434
3000 0.05245190113782883
4000 0.04201402887701988
5000 0.0349687822163105
6000 0.029909880831837654
7000 0.026108812540769577
8000 0.023152366280555725
9000 0.020789247006177902
10000 0.018858611583709717
